name: 'SemVer workflow'
description: 'Updates version tags, creates release branches'
author: 'kvendingoldo'
inputs:
  action:
    description: 'bump-and-tag or make-release'
    default: 'bump-and-tag'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
